### ISSUE TITLE
Product Branches

### ISSUE THREAD

**Issue by andy-hugecalf** [microsoft/PackageUploader#18]
I can't see a way to get a list of branches for a certain product - is this currently possible or, if not, are there any plans to add this functionality?

Cheers,
Andy

**Comment by lawhelpt** [comment]
[Current Operations](https://github.com/microsoft/PackageUploader/tree/main/src/PackageUploader.Application/Operations)

Sorry, does look like we don't have a public operation to support it.

It wouldn't be that hard really to add it, since we get branches in the code elsewhere, its just a matter of exposing that neatly along with the other operations. I would be interested in hearing more about your use case and why you want to list branches?

Do you just want a list of branch names, or current packages etc. in them?
Would you want flights as well?
What would you do with the information?

**Comment by andy-hugecalf** [comment]
We have a build management tool which lists all branches on steam and provides various actions based off this. I am expanding this tool to work for Xbox and I would also like to list all available branches for a certain product. Otherwise, I will have to hardcode them into some config file which isn't great.

Having dug into the code a bit more I can see the http request where you get the branches, and I have successfully made a call and got the branch list for our application. So, for now, I will either directly call this or modify the client api project to expose this.

Is there any documentation for the http api? I have found the docs for the partner centre api, but I can't see any of the calls I see in this application.

Cheers

**Comment by lawhelpt** [comment]
That's good news you can just grab them directly, sorry I didn't think to recommend that path! If you ever do a fork and a meaningful update to the client API do please consider a PR back to help others in the community coming across this :)

@Seann-Murdock do the HTTP APIs have public documentation?

**Comment by Seann-Murdock** [comment]
Currently these APIs aren't supported outside of their use in the package uploader tool so they are not documented.

**Comment by andy-hugecalf** [comment]
Thanks both!

**Comment by alberto-baron** [comment]
Hi @andy-hugecalf , I have spent some time looking into this and I have created a branch which supports returning a list of branches/flights.

You can see the branch in [here](https://github.com/microsoft/PackageUploader/tree/retry_and_branch_list) and a pre-release with the binaries in [here](https://github.com/microsoft/PackageUploader/releases/tag/v1.3.0-beta).

Let me know if it's useful.

Thanks
